Add missing status constant "failed" on refunds
mollie/mollie-api-php pull request #505
Opened 2020-10-28 10:04 UTC by SanderVanLeeuwen

2020-10-28 11:04 UTC, sandervanhooft commented
Hi @SanderVanLeeuwen ,

Nice! Could you provide a matching test for that filter?

2020-11-10 15:53 UTC, SanderVanLeeuwen commented
To be honest I don't have a lot of experience with writing tests. Not sure too how to simulate the `update()` call as a whole and if that's even possible. But would this code separation and test (see additional commit) be adequate? It feels like a lot of things aren't covered yet, but at least it does cover the newly added filter ;)

2020-11-11 09:23 UTC, sandervanhooft requested changes
Hi @SanderVanLeeuwen ,

I think your approach is fine here. Only one little remark, after that it's ready for merge.

2020-11-11 09:23 UTC, sandervanhooft commented on src/Resources/OrderLine.php
> +    public function getData()
Can you rename this to `getUpdateData`?

2020-11-11 09:31 UTC, SanderVanLeeuwen commented on src/Resources/OrderLine.php
> +    public function getData()
Done. I had named it like that originally but renamed it to `getData` because it can get the orderLine data regardless of updating or not. But this sounds reasonable as well ;)

2020-11-11 09:43 UTC, sandervanhooft approved these changes

2020-11-24 13:21 UTC, merged

2020-11-24 13:22 UTC, sandervanhooft commented
Thanks @SanderVanLeeuwen !

2020-11-25 09:07 UTC, sandervanhooft commented
Released in [v2.25.0](https://github.com/mollie/mollie-api-php/releases/tag/v2.25.0)