[WIP] - Add Mollie payment links feature
mollie/mollie-api-php pull request #559
Opened 2021-06-03 11:18 UTC by ciungulete

2021-06-07 10:48 UTC, sandervanhooft requested changes

2021-06-07 10:48 UTC, sandervanhooft commented on src/Endpoints/PaymentLinksEndpoint.php
> +class PaymentLinksEndpoint extends CollectionEndpointAbstract
Rename to singular `PaymentLinkEndpoint`

2021-06-07 10:48 UTC, sandervanhooft commented on src/Resources/PaymentLinkCollection.php
> +        return "paymentLink";
Plural: `paymentLinks`

2021-06-15 12:53 UTC, sandervanhooft requested changes
Any tests yet? 😄

2021-06-15 12:53 UTC, sandervanhooft commented on src/Resources/PaymentLinkCollection.php
> +        return "paymentLinks";
I'm checking this with Mollie. The docs state both `paymentLinks` and `payment_links`

2021-06-18 15:39 UTC, skipworkgh commented
Any ETA on this feature?

2021-06-18 21:53 UTC, sandervanhooft commented
Can't put a date on it but I have been told it's close. 😀

2021-06-21 13:42 UTC, sandervanhooft commented on src/Resources/PaymentLinkCollection.php
> +        return "paymentLinks";
According to the API team it's `payment_links`.

2021-06-23 12:14 UTC, sandervanhooft approved these changes

2021-06-23 12:14 UTC, merged