Add update method to endpoints
mollie/mollie-api-php pull request #570
Opened 2021-07-16 13:20 UTC by ciungulete

- [x] OrderEndpoint
- [x] OrderLineEndpoint
- [x] ShipmentEndpoint
- [x] CustomerEndpoint
- [x] SubscriptionEndpoint
- [x] ProfileEndpoint

2021-07-27 13:37 UTC, sandervanhooft requested changes
Some minor stuff.

2021-07-27 13:37 UTC, sandervanhooft commented on examples/orders/update-order-line.php
> + * How to prepare a new payment with the Mollie API.
How to update an order line with the Mollie API

2021-07-27 13:37 UTC, sandervanhooft commented on examples/orders/update-order.php
> + * How to prepare a new payment with the Mollie API.
How to update an order with the Mollie API

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/CustomerEndpoint.php
> +     * Update the given Customer.
Update a specific Customer resource.

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/CustomerEndpoint.php
> +     * Will throw a ApiException if the order id is invalid or the resource cannot be found.
Will throw ~a~ **an** ApiException

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/OrderEndpoint.php
> +     * Update the given Order.
Update a specific Order resource

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/OrderLineEndpoint.php
> +     * Will throw a ApiException if the subscription id is invalid or the resource cannot be found.
- Update a specific OrderLine resource.

- an ApiException

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/ProfileEndpoint.php
> +    public function update($profileID, array $data = [])
Update a specific Profile resource.

an ApiException

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/ShipmentEndpoint.php
> +     * Update the given Shipment.
Update a specific Order Shipment resource.

an ApiException

2021-07-27 13:37 UTC, sandervanhooft commented on src/Endpoints/SubscriptionEndpoint.php
> +     * Update the given Subscription.
Update a specific Subscription resource.

an ApiException

2021-07-27 19:38 UTC, ciungulete commented on src/Endpoints/ProfileEndpoint.php
> +    public function update($profileID, array $data = [])
and `$profileId`

2021-07-28 16:30 UTC, sandervanhooft approved these changes

2021-07-28 16:30 UTC, merged