Updates for PhpStan Level 2
mollie/mollie-api-php pull request #605
Opened 2022-03-04 09:21 UTC by ciungulete

2022-03-04 10:10 UTC, sandervanhooft requested changes

2022-03-04 10:10 UTC, sandervanhooft commented on src/Endpoints/SubscriptionEndpoint.php
> +     * @return \Mollie\Api\Resources\BaseResource|null
We'll need to override this behaviour somehow, having `Order` here is more convenient

2022-03-04 10:10 UTC, sandervanhooft commented on tests/Mollie/API/Endpoints/MandateEndpointTest.php
> +        /** @var Mandate $mandates */
Collection?

2022-03-04 10:10 UTC, sandervanhooft commented on src/HttpAdapter/Guzzle6And7MollieHttpAdapter.php
> +     * @param string $headers
Please double check the adapters etc. Headers typically is an array, I suspect the same for httpBody but for that one I am not entirely sure.

2022-03-04 10:10 UTC, sandervanhooft commented on src/HttpAdapter/MollieHttpAdapterInterface.php
> +     * @param string $httpBody
Please double check the adapters etc. Headers typically is an array, I suspect the same for httpBody but for that one I am not entirely sure.

2022-03-04 10:10 UTC, sandervanhooft commented on src/MollieApiClient.php
> +    public function getApiKey()
Please don't, for security reasons.

2022-03-04 10:10 UTC, sandervanhooft commented on src/MollieApiClient.php
> +    public function getHttpClient()
Why?

2022-03-04 10:10 UTC, sandervanhooft commented on src/Resources/BaseResource.php
> +/**
Remove/suppress

2022-03-04 10:10 UTC, sandervanhooft commented on src/Resources/Refund.php
> +
Remove/suppress

2022-03-04 10:10 UTC, sandervanhooft commented on tests/Mollie/TestHelpers/FakeHttpAdapter.php
> +     * @param string $httpBody
Please double check the adapters etc. Headers typically is an array, I suspect the same for httpBody but for that one I am not entirely sure.

2022-03-04 11:29 UTC, ciungulete commented on src/HttpAdapter/Guzzle6And7MollieHttpAdapter.php
> +     * @param string $headers
Is declared as string in the rest of the files

2022-03-04 11:34 UTC, ciungulete commented on src/MollieApiClient.php
> +    public function getHttpClient()
https://github.com/mollie/mollie-api-php/blob/269c241956cde41d75565084665d59fe5dd95701/tests/Mollie/API/MollieApiClientTest.php#L130

Is a protected property :-) and PHP Stan found error ```Access to protected property Mollie\Api\MollieApiClient::$httpClient. ```

2022-03-04 11:49 UTC, sandervanhooft commented on src/MollieApiClient.php
> +    public function getHttpClient()
Yes but it's only accessed on the liberated (Liberator) instance for testing, so practically it doesn't make sense to have it there

2022-03-04 12:39 UTC, ciungulete commented on src/Resources/BaseResource.php
> +/**
What you mean?

2022-03-07 11:19 UTC, holtkamp commented on composer.json
> +    "phpstan/phpstan": "^1.4"
might be better to put `phpstan/phpstan` to `require-dev` section?

2022-03-07 14:32 UTC, sandervanhooft requested changes

2022-03-07 14:32 UTC, sandervanhooft commented on src/Endpoints/SubscriptionEndpoint.php
> +     * @return \Mollie\Api\Resources\BaseResource|null
Sorry, I meant `Subscription` here.

2022-03-07 14:32 UTC, sandervanhooft commented on src/MollieApiClient.php
> +     * @var Guzzle6And7MollieHttpAdapter
Just dived into the code, I think this still should be a `MollieHttpAdapterInterface`

2022-03-07 14:32 UTC, sandervanhooft commented on src/MollieApiClient.php
> +    public function getApiKey()
We really need to drop this method somehow

2022-03-07 14:32 UTC, sandervanhooft commented on tests/Mollie/API/MollieApiClientTest.php
> -        $this->assertEmpty($client_copy->apiKey, "API key should not have been remembered");
Can we override phpstan here somehow to keep using `->apiKey` and `->httpClient` on the liberated instance, instead of using getters?

2022-03-07 14:32 UTC, sandervanhooft commented on composer.json
> +    "phpstan/phpstan": "^1.4"
☝️ @ciungulete 😄

2022-03-16 11:52 UTC, ciungulete commented on tests/Mollie/API/Endpoints/MandateEndpointTest.php
> +        /** @var Mandate $mandates */
`$mandates = $customer->mandates();` this return collection and the `@var` is for `$mandates`

2022-03-16 11:53 UTC, ciungulete commented on src/HttpAdapter/MollieHttpAdapterInterface.php
> +     * @param string $httpBody
All are declared as a string in the rest of files

2022-03-16 11:54 UTC, ciungulete commented on src/MollieApiClient.php
> +    public function getApiKey()
Removed

2022-03-16 12:01 UTC, ciungulete commented on src/MollieApiClient.php
> +     * @var Guzzle6And7MollieHttpAdapter
PHP Stan 
`  455    Call to an undefined method Mollie\Api\HttpAdapter\MollieHttpAdapterInterface::enableDebugging().   
  475    Call to an undefined method Mollie\Api\HttpAdapter\MollieHttpAdapterInterface::disableDebugging().  
`

2022-03-16 12:02 UTC, ciungulete commented on src/MollieApiClient.php
> +     * @var Guzzle6And7MollieHttpAdapter
After I replace with `Guzzle6And7MollieHttpAdapter` with `MollieHttpAdapterInterface`

2022-03-17 10:09 UTC, sandervanhooft commented on src/MollieApiClient.php
> +     * @var Guzzle6And7MollieHttpAdapter
I'm ok with suppressing these errors in the php stan neon file.

`455 Call to an undefined method Mollie\Api\HttpAdapter\MollieHttpAdapterInterface::enableDebugging(). 475 Call to an undefined method Mollie\Api\HttpAdapter\MollieHttpAdapterInterface::disableDebugging().`

2022-03-17 10:10 UTC, sandervanhooft commented on tests/Mollie/API/Endpoints/MandateEndpointTest.php
> +        /** @var Mandate $mandates */
👍 Ah yes now I see

2022-03-18 08:57 UTC, sandervanhooft commented on phpstan.neon
> +            - '#Call to an undefined method Tests\\Mollie\\Api\\Endpoints\\CustomerPaymentEndpointTest::createPayment#'
@ciungulete can you point me to the line that triggers this error?

2022-03-19 16:08 UTC, ciungulete commented on phpstan.neon
> +            - '#Call to an undefined method Tests\\Mollie\\Api\\Endpoints\\CustomerPaymentEndpointTest::createPayment#'
`Call to an undefined method Tests\Mollie\Api\Endpoints\CustomerPaymentEndpointTest::createPayment().`

2022-03-19 16:09 UTC, ciungulete commented on phpstan.neon
> +            - '#Call to an undefined method Tests\\Mollie\\Api\\Endpoints\\CustomerPaymentEndpointTest::createPayment#'
My bad

2022-03-24 12:35 UTC, sandervanhooft approved these changes
Nice!

2022-03-24 12:35 UTC, merged