Adding reason and reversedAt attributes to Chargeback resource
mollie/mollie-api-php pull request #615
Opened 2022-04-08 09:39 UTC by dmdijkslag

Mollie has 2 additional attributes for its chargebacks endpoint, see https://docs.mollie.com/reference/v2/chargebacks-api/get-payment-chargeback for more info.

This will update the Chargeback resourse with the additional attributs.

For possible reason codes see https://help.mollie.com/hc/nl/articles/115000309865

2022-04-12 14:35 UTC, sandervanhooft commented
Thanks @dmdijkslag ! You're right. Only one remark:

2022-04-12 14:36 UTC, sandervanhooft commented on src/Resources/Chargeback.php
> +     * @var \stdClass
`reason` can be `null`. It's only included on `directdebit` transactions

2022-04-12 14:36 UTC, sandervanhooft requested changes
reason can be `null`

2022-04-13 06:55 UTC, dmdijkslag commented
@sandervanhooft thanx for the update, you are right. 
I updated the resource and test.

2022-04-21 11:20 UTC, sandervanhooft approved these changes

2022-04-21 11:20 UTC, merged

2022-04-21 11:20 UTC, sandervanhooft commented
Thanks @dmdijkslag !