add create client-links endpoint
mollie/mollie-api-php pull request #687
Opened 2023-06-19 10:41 UTC by Naoray

2023-06-21 12:27 UTC, lucasfeliciano requested changes
Hi, thank you so much for this PR.

I've tested and I found some minor details. Mostly because wrong information in our documentation.

I'll make sure to have it fixed on our side.

2023-06-21 12:27 UTC, lucasfeliciano commented on src/Resources/ClientLink.php
> +            'scopes' => implode('+', $scopes),
There is a typo in our documentation, it should be `scope` instead of `scopes`. 
I'll also fix the docs.

Also, I had to change the character to implode, in the example in the documentation we have the encoded URL.
`http_build_query` encodes space as `+`. 

```suggestion
            'scope' => implode(' ', $scopes),
```

2023-06-21 12:27 UTC, lucasfeliciano commented on src/Resources/ClientLink.php
> +    public function getRedirectUrl(string $client_id, string $state, string $approval_prompt, array $scopes = [])
We don't require `approval_prompt`, instead we have `auto` as default.

```suggestion
    public function getRedirectUrl(string $client_id, string $state, array $scopes = [], string $approval_prompt= 'auto')
```

2023-06-21 12:27 UTC, lucasfeliciano commented on src/Endpoints/ClientLinkEndpoint.php
> +    public function create(array $data = [], array $filters = []): ClientLink
Genuine question:

Why the `$filters` parameter? I don't think it is used at all.

2023-06-22 07:53 UTC, sandervanhooft commented on src/Endpoints/ClientLinkEndpoint.php
> +    public function create(array $data = [], array $filters = []): ClientLink
@lucasfeliciano Good catch. It's there for consistency with other endpoints mostly. It can be removed. But in 90% of the cases I see it then getting added within the year. What do you prefer?

2023-06-22 08:56 UTC, lucasfeliciano commented on src/Endpoints/ClientLinkEndpoint.php
> +    public function create(array $data = [], array $filters = []): ClientLink
Thanks for clarifying @sandervanhooft 

I would rather remove to provide a good developer experience.
It could be confusing to pass a filter and don't see it being reflected in the response

If we need in the future, we can add it. 🙏

2023-06-22 08:57 UTC, sandervanhooft commented on src/Endpoints/ClientLinkEndpoint.php
> +    public function create(array $data = [], array $filters = []): ClientLink
Agreed!

2023-06-23 09:10 UTC, merged