V3
mollie/mollie-api-php pull request #727
Opened 2024-06-24 22:34 UTC by Naoray

Description will follow

2025-01-06 11:10 UTC, sandervanhooft commented on src/EndpointCollection/BalanceEndpointCollection.php
> +    public function get(string $id, $testmode = []): Balance
I get where it's coming from, but that dual use of the testmode parameter is confusing.

How about

```php
public function get(string $id, $parameters = [], $testmode = false): Balance;

// This way it's perfectly clear plus you'd still have the named parameter shortcut (assuming php >8.0)
$mollie->balances->get('bal_123', testmode: true);
```

(This also goes for other implementations of this testmode parameter pattern)

2025-01-06 11:16 UTC, sandervanhooft commented on src/EndpointCollection/MandateEndpointCollection.php
> +    public function createFor(Customer $customer, $payload = [], bool $testmode = false): Mandate
Let's go explicit here: `createForCustomer`, `createForCustomerId` etc.

2025-01-06 12:50 UTC, Naoray commented on .github/workflows/check_php_syntax.yml
> +        php: [7.4]
Depends. If our examples should use php7.4 compatible code, than this action makes sure that this is the case. If we want to switch strategies and only show code for newer PHP versions - which I'd be in favor of - than we can get rid of this workflow.

2025-01-06 12:57 UTC, Naoray commented on .github/workflows/fix-codestyle.yml
> +        run: composer global require laravel/pint
It's only for that workflow and it just works. Not sure why I switched. But pint is only installed in dev dependencies and it's not only used for laravel projects, it's usable for any php project.

2025-01-06 12:59 UTC, Naoray commented on composer.json
> +    "brianium/paratest": "^6.11",
nope, still using it here https://github.com/mollie/mollie-api-php/blob/v3/.github/workflows/tests.yml#L36

2025-01-06 13:00 UTC, Naoray commented on docs/endpoint-collections.md
> +# Introduction
good catch!

2025-01-06 13:03 UTC, Naoray commented on src/CompatibilityChecker.php
> +    public const MIN_PHP_VERSION = '7.4';
What would you want to check on curl?

2025-01-06 13:09 UTC, Naoray commented on src/EndpointCollection/BalanceEndpointCollection.php
> +    public function get(string $id, $testmode = []): Balance
agree. Changed!

2025-01-06 13:11 UTC, Naoray commented on src/EndpointCollection/MandateEndpointCollection.php
> +    public function createFor(Customer $customer, $payload = [], bool $testmode = false): Mandate
✅

2025-01-06 13:14 UTC, Naoray commented on scoper.inc.php
> -<?php declare(strict_types=1);
Didn't know where this was used, that's why I deleted it. But I noticed now it's used in the `create-zip` workflow. Can we then drop that as well?

2025-01-06 13:40 UTC, sandervanhooft commented on .github/workflows/fix-codestyle.yml
> +        run: composer global require laravel/pint
then revert to php-cs-fixer

2025-01-06 13:40 UTC, sandervanhooft commented on composer.json
> +    "brianium/paratest": "^6.11",
perfect, let's keep it then.

2025-01-06 13:44 UTC, sandervanhooft commented on .github/workflows/check_php_syntax.yml
> +        php: [7.4]
Ah wait, phpstan can but we'd have to define it on the phpstan.neon yml, which is very inconvenient in this pipeline. Let's keep the current action.

2025-01-06 13:44 UTC, sandervanhooft commented on scoper.inc.php
> -<?php declare(strict_types=1);
yes, let's remove that for now

2025-01-06 13:49 UTC, sandervanhooft commented on src/CompatibilityChecker.php
> +    public const MIN_PHP_VERSION = '7.4';
Similar to checking the json extension. I've encountered environments where curl wasn't available 🙀 

https://github.com/mollie/mollie-api-php/blob/bbf1ac9d219d6f920c85f0c983f13e7c8fd0f3d3/src/CompatibilityChecker.php#L33-L38

2025-01-07 08:50 UTC, Naoray commented on docs/responses.md
> +$response = $mollie->send(new GetPaymentRequest('tr_*********'));
Ah, good catch. I forgot to update that documentation. By default the resource gets hydrated!

2025-01-07 08:55 UTC, Naoray commented on docs/responses.md
> +$response = $mollie->send(new GetPaymentRequest('tr_*********'));
fixed.

2025-01-07 08:56 UTC, Naoray commented on docs/responses.md
> +If you prefer the old approach of directly receiving the Resource class, you can enable **auto-hydration** by calling `MollieApiClient::setAutoHydrate()`.
the hydration happens by default. Earlier version of the v3 did it manually but it did only add more complexity without gaining much.

2025-01-07 08:57 UTC, Naoray commented on docs/testing.md
> +$customer = $mollie->customers->get('cust_12345678', testmode: true);
do we want to use php7.4 in our docs? I think this just illustrates well what the second param is used for.

2025-01-07 09:12 UTC, Naoray commented on docs/http-adapters.md
> +### Debugging
Currently what we is to just not parse the request to the thrown `ApiException` if debugging is enabled. But we only do this if `GuzzleMollieHttpAdapter` or `PSR18MollieHttpAdapter` is used. This doesn't help the dev using our sdk with debugging, it just prevents sensitive information from being accidentally leaked to third party logging providers.

We could add something like [Saloon's Debugging feature](https://docs.saloon.dev/the-basics/debugging) where the dev can actually see what request and response is sent/retrieved.

2025-01-20 11:06 UTC, sandervanhooft requested changes
Getting there!

- [ ] Double check all testmode parameters: typing (also on docblocks)
- [ ] Double check all testmode parameters: presence. I.e. mandate.revokeForCustomerId vs mandate.revokeForCustomer.

I am now going to spin up a test/demo environment.

2025-01-20 11:06 UTC, sandervanhooft commented on src/EndpointCollection/CustomerEndpointCollection.php
> +    public function update(string $id, $data = []): ?Customer
Checking on the Mollie Slack if the testmode parameter is intentionally omitted from the docs here.

2025-01-20 11:53 UTC, Naoray commented on .github/workflows/create_scoped_zip.yml
> +              'prefix' => 'MollieVendor',
Why pollute the repo with a file if we can have it in the workflow?

2025-01-20 11:59 UTC, Naoray commented on composer.json
> +    "format": "./vendor/bin/pint"
Well.. you wanted to use cs.. so this is just something I forgot to change back. On second thought, we could just add cs fixer on the workflow so we don’t have to remove it in the tests workflow

2025-01-20 12:02 UTC, Naoray commented on docs/responses.md
> +# Responses
Why? It s only stating what we discussed. By default all responses are hydrated.

2025-01-20 22:03 UTC, Naoray commented on src/EndpointCollection/BalanceEndpointCollection.php
> +     * @param  bool|array  $testmode
good question.. We want to allow legacy code so to prevent any errors I think we should not type it since arrays should be acceptable as well

2025-01-21 10:38 UTC, Naoray commented on UPGRADING.md
> +### Type cast embeded Resources
upgrading is not rdy for review. As stated in previous conversations, the `UPGRADING.md` is the last file I want to rework

2025-01-21 10:52 UTC, Naoray commented on docs/debugging.md
> +$mollie->debug(); // Enables both request and response debugging
No, there is not. But I don't see where it would be useful to have this functionality. Typically, you would use `$mollie->debug()->send(...)` within a context and be done with it.

You can as well just debug a specific request `$mollie->send($request->debug())`, that way it's scoped to the request already.

2025-01-22 10:09 UTC, sandervanhooft commented on .github/workflows/create_scoped_zip.yml
> +              'prefix' => 'MollieVendor',
I can appreciate that perspective as well :)

2025-01-22 10:09 UTC, sandervanhooft commented on src/EndpointCollection/CustomerEndpointCollection.php
> +    public function update(string $id, $data = []): ?Customer
Exactly

2025-04-14 11:51 UTC, merged