Enhanced methods.allActive() for integration consistency and added methods.list()
mollie/mollie-api-php pull request #735
Opened 2024-07-10 11:10 UTC by sandervanhooft

This PR ensures integration consistency: `methods.allActive()` now returns the full set of activated methods regardless the currencies supported.

Context: Mollie added support for `twint` recently, which does not appear on `/v2/methods` by default because Twint does not support the `EUR` currency.

To mirror the API, the `list()` method is added for directly interacting with `v2/methods`.

```php
$mollie->methods->list(); // Directly interact with the "/v2/methods" endpoint
$mollie->methods->allActive(); // Enhanced for consistency: returns all methods regardless the currencies supported
```

2024-07-10 12:44 UTC, fjbender requested changes

2024-07-10 12:44 UTC, fjbender commented on src/Endpoints/MethodEndpoint.php
> +        });
`PaymentMethodStatus::ACTIVATED` is for live mode, in test mode `PaymentMethodStatus::ACTIVATED` and the `PENDING` status should be considered. See https://arc.net/l/quote/pgdugzxj

2024-07-10 12:44 UTC, fjbender commented on tests/Mollie/API/Endpoints/MethodEndpointTest.php
> +        );
As `sofort` has been deprecated, maybe we should consider updating this test :)

2024-07-10 12:44 UTC, fjbender commented on tests/Mollie/API/Endpoints/MethodEndpointTest.php
> +            new Response(
Aren't we missing the `status` here, too?

2024-07-10 12:50 UTC, fjbender commented
> `methods.allActive()` now returns the full set of activated methods regardless the currencies supported.

Should we consider this a "soft" BC-break? Or is the filter behavior retained when we specify e.g. amount and currency filter conditions?

2024-07-12 10:33 UTC, sandervanhooft commented on tests/Mollie/API/Endpoints/MethodEndpointTest.php
> +        );
Done, switched to creditcard (Karte)

2024-07-12 10:38 UTC, sandervanhooft commented on tests/Mollie/API/Endpoints/MethodEndpointTest.php
> +            new Response(
:+1: Added to stubs for consistency.

2024-07-12 11:15 UTC, sandervanhooft commented on src/Endpoints/MethodEndpoint.php
> +        });
@fjbender Which `pending` statuses should I check for? Assuming only `pending-review`?

<img width="1654" alt="image" src="https://github.com/user-attachments/assets/6ce24fd2-e925-486f-ba69-8a07ad9ea992">

2024-07-16 08:24 UTC, Naoray commented on src/Endpoints/MethodEndpoint.php
> +        $result = $this->client->performHttpCall("GET", $url);
why not use the existing `allAvailable()` method here which already fetches the `methods/all` endpoint

```suggestion
        $result = $this->allAvailable($parameters);
```

2024-07-17 06:01 UTC, sandervanhooft commented
Closing this for now

2024-07-17 06:01 UTC, closed without merging