Feature/add sales invoices endpoint
mollie/mollie-api-php pull request #756
Opened 2024-12-10 13:09 UTC by Naoray

2024-12-10 19:30 UTC, sandervanhooft requested changes

2024-12-10 19:30 UTC, sandervanhooft commented on examples/sales-invoices/create-sales-invoice.php
> +        'paymentTerm' => PaymentTerm::DAYS_30,
This Type does not exist, perhaps for the better.

2024-12-10 19:30 UTC, sandervanhooft commented on phpstan-baseline.neon
> +			message: "#^Access to constant DAYS_30 on an unknown class Mollie\\\\Api\\\\Types\\\\PaymentTerm\\.$#"
Phpstan picked up on it too

2024-12-11 15:57 UTC, Naoray commented on examples/sales-invoices/create-sales-invoice.php
> +        'paymentTerm' => PaymentTerm::DAYS_30,
I don't think having this type d be bad.

2024-12-12 22:45 UTC, sandervanhooft commented on examples/sales-invoices/create-sales-invoice.php
> +        'paymentTerm' => PaymentTerm::DAYS_30,
Let's add it :+1:

2024-12-12 22:46 UTC, sandervanhooft commented on src/Types/SalesInvoiceStatus.php
> +    const DRAFT = 'draft';
These constants can be marked as `public`

2024-12-18 12:25 UTC, sandervanhooft approved these changes

2024-12-18 12:25 UTC, merged